version: 2.1
orbs:
  node: circleci/node@12
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd client
            - run: npm install
workflows:
    build-and-test:
      jobs:
        - build-and-test