export const USER_AUTHENTICATION_REQUEST = 'USER_AUTHENTICATION_REQUEST';
export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_FAILED = 'USER_AUTHENTICATION_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const { SERVER_URL } = process.env;
