# name of the workflow
name: super linter
# Define Event
on: push
# Define Job 
jobs: 
  linter:
    runs-on: ubuntu-latest
# Steps
  steps: 
    - name: Run linter on this workflow
    - uses: action/checkout@v2
    - name: running linter 
    - run: npm run lint
